format_version: 10
pipelines:
  MyFirstPipeline2:
    group: pipiline_group_a
    label_template: ${COUNT}
    lock_behavior: none
    display_order: -1
    materials:
      git-alias-yo:
        git: https://github.com/suwat-netprom/test.git
        shallow_clone: false
        auto_update: true
        branch: master
    stages:
    - defalutState:
        fetch_materials: true
        keep_artifacts: false
        clean_workspace: false
        approval:
          type: success
          allow_only_on_success: false
        jobs:
          defaultJob:
            timeout: 0
            tasks:
            - exec:
                command: cat new.txt
                run_if: passed
